### ISSUE TITLE
BUG: *Urgent* Info in the "About" section is incorrect

### ISSUE THREAD

**Issue by leviport** [ahoneybun/website#3]
![2023-01-27_12-52-44](https://user-images.githubusercontent.com/13512097/215184636-128dc56d-9bf9-4f9d-9cc4-3edbe654a9fb.png)

**Comment by 13r0ck** [comment]
This is what #2 was referring to

**Comment by 13r0ck** [comment]
:ambulance:

**Comment by 13r0ck** [comment]
:helicopter:

**Comment by 13r0ck** [comment]
:police_car:
